[2023-12-30T17:56:03.865+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KOH.evaluate manual__2023-12-30T12:48:04.791132+00:00 [queued]>
[2023-12-30T17:56:03.885+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KOH.evaluate manual__2023-12-30T12:48:04.791132+00:00 [queued]>
[2023-12-30T17:56:03.885+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-30T17:56:03.917+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): evaluate> on 2023-12-30 12:48:04.791132+00:00
[2023-12-30T17:56:03.921+0500] {standard_task_runner.py:57} INFO - Started process 23717 to run task
[2023-12-30T17:56:03.932+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'KOH', 'evaluate', 'manual__2023-12-30T12:48:04.791132+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/text.py', '--cfg-path', '/tmp/tmp341jehkv']
[2023-12-30T17:56:03.934+0500] {standard_task_runner.py:85} INFO - Job 372: Subtask evaluate
[2023-12-30T17:56:04.013+0500] {task_command.py:416} INFO - Running <TaskInstance: KOH.evaluate manual__2023-12-30T12:48:04.791132+00:00 [running]> on host vm2.myguest.virtualbox.org
[2023-12-30T17:56:04.088+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Admin' AIRFLOW_CTX_DAG_ID='KOH' AIRFLOW_CTX_TASK_ID='evaluate' AIRFLOW_CTX_EXECUTION_DATE='2023-12-30T12:48:04.791132+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-30T12:48:04.791132+00:00'
[2023-12-30T17:56:04.091+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-30T17:56:04.092+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/kda/ML_lab3/MLops_lab3/ && python /home/kda/ML_lab3/MLops_lab3/scripts/evaluate.py']
[2023-12-30T17:56:04.114+0500] {subprocess.py:86} INFO - Output:
[2023-12-30T17:56:05.582+0500] {subprocess.py:93} INFO - 2023/12/30 17:56:05 INFO mlflow.tracking.fluent: Experiment with name 'tree_model_test' does not exist. Creating a new experiment.
[2023-12-30T17:56:05.997+0500] {subprocess.py:93} INFO - /home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/mlflow/models/signature.py:351: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
[2023-12-30T17:56:05.997+0500] {subprocess.py:93} INFO -   input_schema = _infer_schema(input_example)
[2023-12-30T17:56:06.003+0500] {subprocess.py:93} INFO - /home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/mlflow/models/signature.py:362: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
[2023-12-30T17:56:06.003+0500] {subprocess.py:93} INFO -   output_schema = _infer_schema(prediction)
[2023-12-30T17:56:09.178+0500] {subprocess.py:93} INFO - 2023/12/30 17:56:09 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under /home/kda/ML_lab3/MLops_lab3/mlflow/5/d8d00752eb08455a80a26719add0ab2c/artifacts. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.
[2023-12-30T17:56:09.215+0500] {subprocess.py:93} INFO - Registered model 'tree' already exists. Creating a new version of this model...
[2023-12-30T17:56:09.324+0500] {subprocess.py:93} INFO - 2023/12/30 17:56:09 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: tree, version 352
[2023-12-30T17:56:09.324+0500] {subprocess.py:93} INFO - Created version '352' of model 'tree'.
[2023-12-30T17:56:09.376+0500] {subprocess.py:93} INFO - /home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/mlflow/models/signature.py:212: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
[2023-12-30T17:56:09.377+0500] {subprocess.py:93} INFO -   inputs = _infer_schema(model_input) if model_input is not None else None
[2023-12-30T17:56:11.877+0500] {subprocess.py:93} INFO - /home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
[2023-12-30T17:56:11.877+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-12-30T17:56:11.877+0500] {subprocess.py:93} INFO - /home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
[2023-12-30T17:56:11.877+0500] {subprocess.py:93} INFO -   warnings.warn("Setuptools is replacing distutils.")
[2023-12-30T17:56:11.926+0500] {subprocess.py:93} INFO - 2023/12/30 17:56:11 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under /home/kda/ML_lab3/MLops_lab3/mlflow/5/d8d00752eb08455a80a26719add0ab2c/artifacts. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.
[2023-12-30T17:56:11.937+0500] {subprocess.py:93} INFO - Registered model 'tree' already exists. Creating a new version of this model...
[2023-12-30T17:56:12.041+0500] {subprocess.py:93} INFO - 2023/12/30 17:56:12 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: tree, version 353
[2023-12-30T17:56:12.042+0500] {subprocess.py:93} INFO - Created version '353' of model 'tree'.
[2023-12-30T17:56:12.098+0500] {subprocess.py:93} INFO -      Price (in USD)  Unnamed: 0.2  Unnamed: 0.1  ...  Z4 M40i  Z4 Roadster     i8
[2023-12-30T17:56:12.099+0500] {subprocess.py:93} INFO - 0             67600           912           912  ...    False        False  False
[2023-12-30T17:56:12.100+0500] {subprocess.py:93} INFO - 1             81250           843           843  ...    False        False  False
[2023-12-30T17:56:12.100+0500] {subprocess.py:93} INFO - 2             69000           293           293  ...    False        False  False
[2023-12-30T17:56:12.100+0500] {subprocess.py:93} INFO - 3            180000           554           554  ...    False        False  False
[2023-12-30T17:56:12.100+0500] {subprocess.py:93} INFO - 4             64695           581           581  ...    False        False  False
[2023-12-30T17:56:12.100+0500] {subprocess.py:93} INFO - ..              ...           ...           ...  ...      ...          ...    ...
[2023-12-30T17:56:12.100+0500] {subprocess.py:93} INFO - 298          250000           951           951  ...    False        False  False
[2023-12-30T17:56:12.100+0500] {subprocess.py:93} INFO - 299         2600000           523           523  ...    False        False  False
[2023-12-30T17:56:12.100+0500] {subprocess.py:93} INFO - 300          103500            61            61  ...    False        False  False
[2023-12-30T17:56:12.100+0500] {subprocess.py:93} INFO - 301          157500           355           355  ...    False        False  False
[2023-12-30T17:56:12.101+0500] {subprocess.py:93} INFO - 302          200000           335           335  ...    False        False  False
[2023-12-30T17:56:12.101+0500] {subprocess.py:93} INFO - 
[2023-12-30T17:56:12.101+0500] {subprocess.py:93} INFO - [303 rows x 220 columns]
[2023-12-30T17:56:12.101+0500] {subprocess.py:93} INFO - 0.26732673267326734
[2023-12-30T17:56:12.734+0500] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-30T17:56:12.767+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=KOH, task_id=evaluate, execution_date=20231230T124804, start_date=20231230T125603, end_date=20231230T125612
[2023-12-30T17:56:12.816+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-30T17:56:12.840+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
